require "tempfile"
require "zip"

class AlbumZipExportJob < ApplicationJob
  queue_as :default

  def perform(export)
    return unless export.queued?

    export.update!(status: :processing, error_message: nil)
    requester = export.requested_by
    assets = export.album.exportable_media_assets_for(requester)
    raise EmptyAlbumError if assets.empty?
    raise OriginalPermissionError if export.include_originals? && !staff?(requester)

    export.update!(media_asset_ids: assets.map(&:id), media_count: assets.length)
    write_archive!(export, assets)
    export.update!(status: :ready, completed_at: Time.current)
  rescue ActiveRecord::RecordNotFound
    # The album, requester, or export was removed while waiting in the queue.
  rescue EmptyAlbumError
    fail_export!(export, "This album has no media you can download.")
  rescue OriginalPermissionError
    fail_export!(export, "Your permission to download original files changed.")
  rescue StandardError => error
    Rails.error.report(error, handled: true, context: { album_export_id: export&.id })
    fail_export!(export, "The album download could not be created. Please try again.")
  end

  private

  EmptyAlbumError = Class.new(StandardError)
  OriginalPermissionError = Class.new(StandardError)

  def write_archive!(export, assets)
    Zip.write_zip64_support = true
    Tempfile.create([ "vowloom-#{export.album.id}-", ".zip" ]) do |file|
      file.binmode
      Zip::OutputStream.open(file.path) do |zip|
        assets.each_with_index { |asset, index| write_asset!(zip, asset, index, originals: export.include_originals?) }
        zip.put_next_entry("README.txt")
        zip.write(readme_for(export, assets.length))
      end
      file.rewind
      export.archive.attach(
        io: file,
        filename: "#{safe_filename(export.album.title)}-#{export.created_at.to_date}.zip",
        content_type: "application/zip"
      )
    end
  end

  def write_asset!(zip, asset, index, originals:)
    zip.put_next_entry(filename_for(asset, index, originals:))
    if asset.image? && !originals
      asset.rendition(:web_download).processed.download { |chunk| zip.write(chunk) }
    else
      asset.file.blob.download { |chunk| zip.write(chunk) }
    end
  end

  def filename_for(asset, index, originals:)
    original = safe_filename(asset.file.filename.to_s)
    extension = if asset.image? && !originals
      ".jpg"
    else
      File.extname(original).presence || ".bin"
    end
    stem = File.basename(original, File.extname(original)).presence || "media"
    format("%03d-%s%s", index + 1, stem, extension)
  end

  def safe_filename(value)
    value.to_s.gsub(/[^A-Za-z0-9._-]/, "_").truncate(160, omission: "")
  end

  def readme_for(export, media_count)
    copy = export.include_originals? ? "original files" : "web-sized images and supplied video files"
    <<~TEXT
      #{export.album.title}

      Generated by Vowloom on #{Time.current.iso8601}.
      This archive contains #{media_count} #{copy}.
      Keep the original Vowloom media storage and database backup as the canonical preservation copy.
    TEXT
  end

  def fail_export!(export, message)
    return unless export&.persisted?

    export.archive.purge if export.archive.attached?
    export.update!(status: :failed, error_message: message, completed_at: Time.current)
  end

  def staff?(user)
    user.owner? || user.admin? || user.helper?
  end
end
